// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reiseplaner.DataAccess;

#nullable disable

namespace Reiseplaner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("Reiseplaner.Models.Programmpunkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Erledigt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kosten")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReiseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReiseId");

                    b.ToTable("Programmpunkte");
                });

            modelBuilder.Entity("Reiseplaner.Models.Reise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enddatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Startdatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zielort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reisen");
                });

            modelBuilder.Entity("Reiseplaner.Models.Programmpunkt", b =>
                {
                    b.HasOne("Reiseplaner.Models.Reise", "Reise")
                        .WithMany("Programmpunkte")
                        .HasForeignKey("ReiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reise");
                });

            modelBuilder.Entity("Reiseplaner.Models.Reise", b =>
                {
                    b.Navigation("Programmpunkte");
                });
#pragma warning restore 612, 618
        }
    }
}
